---

- hosts: all
  become: true
  tasks:

  - name: update repositories
    dnf:
      update_cache: true

  - name: install apache2 packege
    dnf:
      name: httpd
      state: latest

  - name: enable and start service httpd
    systemd:
      name: httpd
      enabled: yes
      state: started

  - name: allow http in firewalld
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

  - name: add php support for apache
    dnf:
      name: php
      state: latest
