---
- hosts: all
  become: true
  vars:
    package_map:
      RedHat: { pkg: ['httpd', 'php'], svc: 'httpd' }
      Rocky: { pkg: ['httpd', 'php'], svc: 'httpd' }
      Debian: { pkg: ['apache2', 'libapache2-mod-php'], svc: 'apache2' }
      Ubuntu: { pkg: ['apache2', 'libapache2-mod-php'], svc: 'apache2' }
  
  tasks:
    - name: Update repositories and install packages
      package:
        name: "{{ package_map[ansible_distribution].pkg }}"
        state: latest
        update_cache: true
      when: ansible_distribution in package_map.keys()

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Enable and start Apache service
      systemd:
        name: "{{ package_map[ansible_distribution].svc }}"
        enabled: yes
        state: started
      when: 
        - ansible_distribution in package_map.keys()
        - package_map[ansible_distribution].svc in ansible_facts.packages

    - name: Allow http in firewalld
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
      when: ansible_distribution in package_map.keys()
