- hosts: all
  become: true
  tasks:
  
    - name: Remove PHP support for Apache
      dnf:
        name: php
        state: absent

    - name: Remove apache2 package
      dnf:
        name: httpd
        state: absent

    - name: Block http in firewalld
      firewalld:
        service: http
        permanent: true
        state: disabled
        immediate: yes
