---
- name: create {{ user_details.name }} user
  user:
    name: "{{ user_details.name }}"
    groups: "{{ user_details.groups }}"
    state: "{{ user_details.state }}"

- name: add ssh key to {{ user_details.name }} user
  authorized_key:
    user: "{{ user_details.name }}"
    state: present
    key: "{{ ssh_key.key }}"

- name: add sudoers file for {{ user_details.name }} user
  copy:
    src: "{{ sudoers_config.src_file }}"
    dest: "{{ sudoers_config.dest_path }}"
    owner: "{{ sudoers_config.owner }}"
    group: "{{ sudoers_config.group }}"
    mode: "{{ sudoers_config.mode }}"