---
- name: Install Apache and PHP
  package:
    name: "{{ package_map[ansible_distribution].pkg }}"
    state: latest
  when: ansible_distribution in package_map.keys()

- name: Copy default_site.html
  copy:
    src: "{{ html_file.src }}"
    dest: "{{ html_file.dest }}"
    owner: "{{ html_file.owner }}"
    group: "{{ html_file.group }}"
    mode: "{{ html_file.mode }}"
  when: ansible_distribution in package_map.keys()

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Enable and restart Apache service
  systemd:
    name: "{{ package_map[ansible_distribution].svc }}"
    enabled: True
    state: restarted
  when: ansible_distribution in package_map.keys() and 
        package_map[ansible_distribution].svc in ansible_facts.packages

- name: Allow http in firewalld
  firewalld:
    service: "{{ firewalld_config.service }}"
    permanent: "{{ firewalld_config.permanent }}"
    state: "{{ firewalld_config.state }}"
    immediate: "{{ firewalld_config.immediate }}"
  when: ansible_distribution in package_map.keys()

- name: change e-mail address for admin
  lineinfile:
    path: "{{ apache_config.path }}"
    regexp: "{{ apache_config.regexp }}"
    line: "{{ apache_config.line }}"
  when: ansible_distribution == 'Rocky'
  notify: restart_apache