---
- name: Install Apache and PHP
  package:
    name: "{{ package_map[ansible_distribution].pkg }}"
    state: latest
  when: ansible_distribution in package_map.keys()

- name: Copy default_site.html
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution in package_map.keys()

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Enable and restart Apache service
  systemd:
    name: "{{ package_map[ansible_distribution].svc }}"
    enabled: yes
    state: restarted
  when: 
    - ansible_distribution in package_map.keys()
    - package_map[ansible_distribution].svc in ansible_facts.packages

- name: Allow http in firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes
  when: ansible_distribution in package_map.keys()

- name: change e-mail address for admin
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: 'ServerAdmin somebody@somewhere.net'
  when: ansible_distribution == 'Rocky'
  register: httpd

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
  when: httpd.changed and ansible_distribution == 'Rocky'